### ISSUE TITLE
оптимизированный select по anime_id

### ISSUE THREAD

**Issue by VVBondarenko** [sovetromantica/sr-api#10]
https://github.com/sovetromantica/sr-api/blob/9c6d0cdcae1ebce9f49cad055cf663aca2392c26/api.pl#L94

запрос можно заменить на 

```
select a.anime_id, a.anime_year, a.anime_name, a.anime_name_russian, a.anime_studio, a.anime_description,
       a.anime_keywords, a.anime_episodes, a.anime_soft_raw_link, a.anime_ongoing, a.anime_folder,
       count(if(e.episode_type = 0, 1, null)) as episode_current_sub,
       count(if(e.episode_type = 1, 1, null)) as episode_current_dub
from anime a join episodes e on a.anime_id = e.episode_anime
where anime_id = 1
group by a.anime_id
limit 1
```

По идее, должно быть чуть оптимальнее, если верить плану выполнения.

Исходный: 
![image](https://user-images.githubusercontent.com/17413802/82765930-ace5b280-9e23-11ea-8603-20807cd69894.png)

Новый:
![image](https://user-images.githubusercontent.com/17413802/82817782-40f85e00-9ea6-11ea-9d02-be41917b885a.png)

**Comment by Disinterpreter** [comment]
Спасибо за новый, эффективный запрос.
https://github.com/sovetromantica/sr-api/commit/64089b2d955b0dc7cb6512c47e27f24eb27b67dc
