### ISSUE TITLE
[Feature Request] ID на Шикимори

### ISSUE THREAD

**Issue by ghost** [sovetromantica/sr-api#11]
Хотелось бы, чтобы в информации об аниме также возвращался ID этого аниме на Шикимори, как это происходит в api вашего ВК приложения (`https://api.sovetromantica.com/api/v1/notify/vkapp/get`)

**Comment by Disinterpreter** [comment]
Добавил возвращаемый параметр anime_shikimori. 
Подробности: https://github.com/sovetromantica/sr-api/commit/7fddf061f42d390f246372d661814bdea1170790
