### ISSUE TITLE
[Feature Request] пагинация в last_episodes

### ISSUE THREAD

**Issue by ghost** [sovetromantica/sr-api#5]
Хотелось бы увидеть пагинацию (например, параметры `?offset` и `?limit`) в методе `/v1/last_episodes`.

**Comment by Disinterpreter** [comment]
Спасибо! Выглядит интересным. Постараюсь сделать.

Дубликат #6

**Comment by AniLabXTeam** [comment]
> Спасибо! Выглядит интересным. Постараюсь сделать.
> 
> Дубликат #6

Почему отмечено как дубликат #6 ? Похожего между фичами только наличии пагинации. Я прошу дать возможность загружать данные каталога, а не последних эпизодов.

**Comment by Disinterpreter** [comment]
> > Спасибо! Выглядит интересным. Постараюсь сделать.
> > Дубликат #6
> 
> Почему отмечено как дубликат #6 ? Похожего между фичами только наличии пагинации. Я прошу дать возможность загружать данные каталога, а не последних эпизодов.

Этот отмечен как дубликат того, что вы сделали позже. Просто я пометил дубликатом тот, в котором меньше информации. Основываться буду на тот. (написал неправильно, этот недополненный дубликат того таска)

**Comment by AniLabXTeam** [comment]
> > > Спасибо! Выглядит интересным. Постараюсь сделать.
> > > Дубликат #6
> > 
> > 
> > Почему отмечено как дубликат #6 ? Похожего между фичами только наличии пагинации. Я прошу дать возможность загружать данные каталога, а не последних эпизодов.
> 
> Этот отмечен как дубликат того, что вы сделали позже. Просто я пометил дубликатом тот, в котором меньше информации. Основываться буду на тот. (написал неправильно, этот недополненный дубликат того таска)

Стоп. Но ведь эта таска не дубликат той таски. Тут человек просит пагинацию по разделу last_episodes. Я же прошу добавить недостающий раздел для пагинации/фильтрации по каталогу Аниме и Дорам. У нас с ним разные запросы и разные задачи, которые будут решать эти разные эндпоинты.

**Comment by Disinterpreter** [comment]
А, окей! В любом случае сделаю обе, когда сяду за этот код.

**Comment by Disinterpreter** [comment]
Простите за столь долгое ожидание.

https://github.com/sovetromantica/sr-api/commit/7cbf7af6376541deddf12534d50e165b76eb9ba3
