### ISSUE TITLE
[Feature Request] Получение данных каталога с пагинацией и фильтрами

### ISSUE THREAD

**Issue by AniLabXTeam** [sovetromantica/sr-api#6]
На данный момент в методах API доступны только **/animesearch** и **/last_episodes** с довольно узкой направленностью. Они не позволяют реализовать "каталог" контента с пагинацией по нему.

Предлагаю добавить новый endpoint: **/list**
Необходим для получения списков контента постранично с применением фильтров (опционально).

Желаемые параметры:
**type** - nullable. тип контента (all (по умолчанию), anime, dorama)
**page** - nullable. номер страницы для выдачи (можно заменить offset, если это удобнее. по умолчанию, 1, если page, 0, если offset)
**limit** - nullable. количество элементов в выдаче (например, от 10 до 100. по умолчанию 20-30)
**genres** - nullable. id жанров через запятую (пример: 1,2,3)
**studio** - nullable. id студии (пример: 33)

Также, можно смержить функционал поиска в этот эндпоинт (или расширить **/animesearch**), ибо на сайте все это добро работает в связке.

В выдаче минимально необходимые данные: id контента, название (англ/ру), обложка. Но, чем больше информации, тем лучше.

**Comment by Disinterpreter** [comment]
Мы прекратили работать с дорамаи, в них мало смысла, да и видео самих на сайте уже нет. Есть ли смысл делать разделение?

**Comment by AniLabXTeam** [comment]
> Мы прекратили работать с дорамаи, в них мало смысла, да и видео самих на сайте уже нет. Есть ли смысл делать разделение?

Тогда смысла разделять нет. Мне казалось, что все еще работаете с дорамами.

**Comment by Disinterpreter** [comment]
9c6d0cdcae1ebce9f49cad055cf663aca2392c26

Сделал пока параметры offset и limit. Над остальным буду думать позже, особенно над жанрами.

![image](https://user-images.githubusercontent.com/3816155/74685985-2ba5d080-51e1-11ea-82bd-b0f713fb55e5.png)
