### ISSUE TITLE
[Feature Request] список онгоингов

### ISSUE THREAD

**Issue by VVBondarenko** [sovetromantica/sr-api#9]
Хотелось бы иметь возможность получать список онгоингов по аналогии с главной страницей. С выбором "страницы" по аналогии с #5

**Comment by Disinterpreter** [comment]
https://github.com/sovetromantica/sr-api/commit/c48cee7063110846fbacb925bf85efc9e2c1cbaa

Сделано. Думаю, айдишников должно хватить. В нашей базе тайтлы не делятся по сезонам, поэтому разделять их в API не очень получится.

**Comment by VVBondarenko** [comment]
Получая только айдишники итоговое количество запросов будет больше: по каждому айдишнику нужно запрашивать инфу или дополнительно кешировать на клиенте/прокси.

**Comment by VVBondarenko** [comment]
Сейчас прилетают онгоинги c anime_disabled. Ловлю ошибки при подгрузке деталей: 
```
id: 997
status: 200
response: {'code': 503, 'description': 'anime rows are empty'}
```

**Comment by Disinterpreter** [comment]
> 
> 
> Получая только айдишники итоговое количество запросов будет больше: по каждому айдишнику нужно запрашивать инфу или дополнительно кешировать на клиенте/прокси.

Мы готовы мириться с этим. 



> 
> 
> Сейчас прилетают онгоинги c anime_disabled. Ловлю ошибки при подгрузке деталей:

По некоторым причинам мы не можем открывать anime_disabled.

**Comment by ghost** [comment]
> По некоторым причинам мы не можем открывать anime_disabled.

Вопрос не про это, текущий запрос возвращает даже "выключенные" аниме. Нужно добавить `and anime_disabled = 0` в запрос

> Мы готовы мириться с этим.

Почему бы просто не добавить полей в `select`, или хотя бы сделать ендпоинт для получения нескольких аниме по ид за раз? Получение аниме по одному будет очень (ОЧЕНЬ) больно в плане скорости работы, как следствие — пострадает UX.

_сейчас гораздо проще парсить html сайта, чем использовать api_

**Comment by Disinterpreter** [comment]
> Почему бы просто не добавить полей в `select`, или хотя бы сделать ендпоинт для получения нескольких аниме по ид за раз? Получение аниме по одному будет очень (ОЧЕНЬ) больно в плане скорости работы, как следствие — пострадает UX.
> 
> _сейчас гораздо проще парсить html сайта, чем использовать api_

Хорошо. Я понял вас. Постараюсь заняться отдельным эндпоинтом. Спасибо за активное участие.

**Comment by Disinterpreter** [comment]
Вот так вот?
#12
